"""
Django settings for project_name project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
import requests

from .secret_settings import *

response_bytes = requests.get('http://ifcfg.me').content
host_ip_address = "".join(map(chr, response_bytes))

EMAC_DOMAIN = "lvh.me"
EMAC_PROTOCOL = "http"


HOST_IP_ADDRESS_1 = "REDACTED" # JPR Redacted Oct. 2024
HOST_IP_ADDRESS_2 = "REDACTED" # JPR Redacted Oct. 2024
HOST_IP_ADDRESS_3 = "REDACTED" # JPR Redacted Oct. 2024
HOST_IP_ADDRESS_4 = "REDACTED" # JPR Redacted Oct. 2024

if host_ip_address.startswith(HOST_IP_ADDRESS_1):
    if host_ip_address == HOST_IP_ADDRESS_2 or host_ip_address == HOST_IP_ADDRESS_3 :
        EMAC_DOMAIN = "emac-dev.gsfc.nasa.gov"
        EMAC_PROTOCOL = "https"
    elif host_ip_address == HOST_IP_ADDRESS_4:
        EMAC_DOMAIN = "emac.gsfc.nasa.gov"
        EMAC_PROTOCOL = "https"

# if EMAC_DOMAIN == "lvh.me":
#     EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False if EMAC_DOMAIN == "emac.gsfc.nasa.gov" else True

ALLOWED_HOSTS = ["*"] if DEBUG else ["emac.gsfc.nasa.gov"]

# redirect back to root after logging in because we are not setting up profile pages
LOGIN_REDIRECT_URL = '/'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    # 'django_recaptcha'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'emac.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'emac', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'emac.emac_context_processors.export_vars',
            ],
        },
    },
]

WSGI_APPLICATION = 'emac.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default' : {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres', 
        'USER': 'postgres', 
        'PASSWORD': EMAC_ADMIN_PASSWORD,
        'HOST': 'website_db',
    },
    'shared': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres', 
        'USER': 'postgres', 
        'PASSWORD': EMAC_ADMIN_PASSWORD,
        'HOST': 'shared_db',
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
MEDIA_URL = '/media/'

DATABASE_ROUTERS = []
DB_IMPORT_IN_PROGRESS = False

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

from website import app_settings

# SILENCED_SYSTEM_CHECKS = [
#     "django_recaptcha.recaptcha_test_key_error"
# ]