{
	"services": {
		"hssi": {
			"build": "./docker",
			"image": "hssi",
			"container_name": "HSSI",
			"depends_on": ["website_db"],
			"ports": ["80:80"],
			"volumes": [
				"./django:/django",
				"./django/static:/static",
				"../../logs/nginx:/var/log/nginx",
				"./config/nginx/logrotate:/etc/logrotate.d/nginx",
				"./config/django:/config/django",
				"./config/nginx:/etc/nginx/conf.d",
				"./pip-requirements:/extensions/pip-requirements"
			],
			"environment": [
				"SUPERUSER_NAME=$SUPERUSER_NAME",
				"SUPERUSER_PWD=$SUPERUSER_PWD",
				"PROJECT_NAME=hssi",
				"APP_NAME=website",
				"GUNICORN_WORKERS=4",
				"GUNICORN_BACKLOG=4096",
				"GUNICORN_BIND=0.0.0.0:8000",
				"GUNICORN_TIMEOUT=3600"
			]
		},
		"website_db": {
			"image": "postgres",
			"container_name": "website_db",
			"environment": [
				"POSTGRES_PASSWORD=$SUPERUSER_PWD"
			],
			"volumes": [
				"website_db_data:/var/lib/postgresql/data"
			]
		}
	},
	"volumes": {
		"website_db_data": {}
	}
}
