version: '3'

services:

    emac:
        build: ./EMAC/docker
        image: emac
        container_name: EMAC
        logging:
            options:
                max-size: "100m"
                max-file: "3"
        depends_on:
            - docker-gen
            - hardcore
            - lightkurve
            - tools
            - website_db
        expose:
            - "80"
        volumes:
            - ../data:/data
            - ../logs/emac/nginx:/var/log/nginx
            - ./shared/config/nginx/logrotate:/etc/logrotate.d/nginx
            - ./EMAC/django:/django
            - ./EMAC/django/static:/static
            - ./shared/config/django:/config/django
            - ./shared/config/nginx:/etc/nginx/conf.d
            - ./shared/django/emac_base_template.html:/django/emac/templates/emac_base_template.html
            - ./shared/django/registration:/django/emac/templates/registration
            - ./shared/django/emac_context_processors.py:/django/emac/emac_context_processors.py
            - ./shared/django/emac_secret_settings.py:/django/emac/emac_secret_settings.py
            - ./shared/django/emac_utils.py:/django/emac/emac_utils.py
            - ./shared/static/emac_apps:/static/emac_apps
            - ./shared/pip-requirements:/extensions/pip-requirements
            - ./shared/django/recaptcha_auth_forms.py:/django/emac/recaptcha_auth_forms.py
        environment:
            - EMAC_ADMIN_USERNAME=$EMAC_ADMIN_USERNAME
            - EMAC_ADMIN_PASSWORD=$EMAC_ADMIN_PASSWORD
            - PROJECT_NAME=emac
            - APP_NAME=website
            - GUNICORN_WORKERS=4
            - GUNICORN_BACKLOG=4096
            - GUNICORN_BIND=0.0.0.0:8000
            - GUNICORN_TIMEOUT=3600
            - VIRTUAL_HOST=$EMAC_DOMAIN

    hardcore:
        image: yosefmiller/hardcore-website
        container_name: hardCORE
        logging:
            options:
                max-size: "100m"
                max-file: "3"
        expose:
            - "80"
        volumes:
            - ../logs/hardcore/nginx:/var/log/nginx
            - ../logs/hardcore/cleanup:/var/log/cleanup
        environment:
            - VIRTUAL_HOST=hardcore.$EMAC_DOMAIN

    lightkurve:
        image: yosefmiller/lightkurve-website
        container_name: Lightkurve
        logging:
            options:
                max-size: "100m"
                max-file: "3"
        expose:
            - "80"
        volumes:
            - ../logs/lightkurve/nginx:/var/log/nginx
            - ../logs/lightkurve/cleanup:/var/log/cleanup
        environment:
            - VIRTUAL_HOST=lightkurve.$EMAC_DOMAIN

    tools:
        build: ./Tools/docker
        image: tools
        container_name: Tools
        logging:
            options:
                max-size: "100m"
                max-file: "3"
        depends_on:
            - shared_db
        expose:
            - "80"
        volumes:
            - ../data:/data
            - ../logs/tools/nginx:/var/log/nginx
            - ./shared/config/nginx/logrotate:/etc/logrotate.d/nginx
            - ./Tools/django:/django
            - ./Tools/django/static:/static
            - ./shared/config/django:/config/django
            - ./shared/config/nginx:/etc/nginx/conf.d
            - ./shared/django/emac_base_template.html:/django/tools/templates/emac_base_template.html
            - ./shared/django/emac_context_processors.py:/django/tools/emac_context_processors.py
            - ./shared/django/emac_secret_settings.py:/django/tools/emac_secret_settings.py
            - ./shared/django/PyMultipolator.py:/django/tools/PyMultipolator.py
            - ./shared/static/emac_apps:/static/emac_apps
        environment:
            - EMAC_ADMIN_USERNAME=$EMAC_ADMIN_USERNAME
            - EMAC_ADMIN_PASSWORD=$EMAC_ADMIN_PASSWORD
            - PROJECT_NAME=tools
            - APP_NAME=tools
            - GUNICORN_WORKERS=4
            - GUNICORN_BACKLOG=4096
            - GUNICORN_BIND=0.0.0.0:8000
            - GUNICORN_TIMEOUT=3600
            - VIRTUAL_HOST=tools.$EMAC_DOMAIN

    nginx-proxy:
        image: owasp/modsecurity-crs:nginx
        container_name: nginx-proxy
        healthcheck:
            disable: true
        logging:
            options:
                max-size: "100m"
                max-file: "3"
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ../certs:/etc/nginx/certs
            - ../logs/nginx-proxy:/var/log/nginx
            - ./shared/config/nginx/logrotate:/etc/logrotate.d/nginx
            - nginx-proxy-conf:/etc/nginx/conf.d
            - nginx-proxy-vhosts:/etc/nginx/vhost.d
            - nginx-proxy-shared-html:/usr/share/nginx/html
            - /var/run/docker.sock:/tmp/docker.sock:ro

    docker-gen:
        image: jwilder/docker-gen
        logging:
            options:
                max-size: "100m"
                max-file: "3"
        container_name: docker-gen
        command: -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
        depends_on:
            - nginx-proxy
        environment:
            - DEFAULT_HOST=$EMAC_DOMAIN
            - GRIDSEARCHER_BACKEND=http://10.82.82.207/
        volumes:
            - ../certs:/etc/nginx/certs:ro
            - ./docker-gen/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
            - nginx-proxy-conf:/etc/nginx/conf.d
            - nginx-proxy-vhosts:/etc/nginx/vhost.d
            - /var/run/docker.sock:/tmp/docker.sock:ro

    shared_db:
        image: postgres
        container_name: shared_db
        logging:
            options:
                max-size: "100m"
                max-file: "3"
        environment:
            - POSTGRES_PASSWORD=$EMAC_ADMIN_PASSWORD
        # To persist db data, uncomment the following volumes statement, and see the outer
        # volumes section below:
        volumes:
            - shared_db_data:/var/lib/postgresql/data

    website_db:
        image: postgres
        container_name: website_db
        logging:
            options:
                max-size: "100m"
                max-file: "3"
        environment:
            - POSTGRES_PASSWORD=$EMAC_ADMIN_PASSWORD
        # To persist db data, uncomment the following volumes statement, and see the outer
        # volumes section below:
        volumes:
            - website_db_data:/var/lib/postgresql/data

# To persist db data, uncomment at least the next two lines, and see the further note below
volumes:
    shared_db_data:  # NOTE that this statement alone persists data in Docker's volume storage
                # area. To clear this data entirely, use: docker volume rm emac_shared_db_data
                # To persist elsewhere, uncomment the following, and make sure a directory
                # exists at the desired location as specified by "device:"
        # driver_opts:
        #     type: none
        #     device: data/db
        #     o: bind
    website_db_data:  # NOTE that this statement alone persists data in Docker's volume storage
                # area. To clear this data entirely, use: docker volume rm emac_website_db_data
                # To persist elsewhere, uncomment the following, and make sure a directory
                # exists at the desired location as specified by "device:"
        # driver_opts:
        #     type: none
        #     device: data/db
        #     o: bind
    nginx-proxy-conf:
    nginx-proxy-shared-html:
    nginx-proxy-vhosts:
