"""
Django settings for hssi project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import requests

from .secret_settings import *

response_bytes = requests.get('http://ifcfg.me').content
host_ip_address = "".join(map(chr, response_bytes))

HSSI_DOMAIN = "lvh.me"
HSSI_PROTOCOL = "http"

HOST_IP_ADDRESS_1 = "REDACTED"
HOST_IP_ADDRESS_2 = "REDACTED"
HOST_IP_ADDRESS_3 = "REDACTED"
HOST_IP_ADDRESS_4 = "REDACTED"
if host_ip_address.startswith(HOST_IP_ADDRESS_1):
    if host_ip_address == HOST_IP_ADDRESS_2 or host_ip_address == HOST_IP_ADDRESS_3:
        HSSI_DOMAIN = "dev_hssi_website.com"
        HSSI_PROTOCOL = "https"
    elif host_ip_address == HOST_IP_ADDRESS_4:
        HSSI_DOMAIN = "main_hssi_website.com"
        HSSI_PROTOCOL = "https"


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False if HSSI_DOMAIN == "main_hssi_website.com" else True

ALLOWED_HOSTS = ["*"] if DEBUG else ["main_hssi_website.com"]

# redirect back to root after logging in because we are not setting up profile pages
LOGIN_REDIRECT_URL = '/'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django_extensions',
    # 'django_recaptcha'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hssi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'hssi', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'hssi.hssi_context_processors.export_vars',
            ],
        },
    },
]

WSGI_APPLICATION = 'hssi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres', 
        'USER': 'postgres', 
        'PASSWORD': ADMIN_PASSWORD,
        'HOST': 'shared_db',
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
MEDIA_URL = '/media/'

DATABASE_ROUTERS = []

from website import app_settings
