# Generated by Django 5.1.5 on 2025-03-25 17:38

import colorful.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
import website.models.old
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('identifier', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FunctionCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(blank=True, max_length=5, null=True)),
                ('backgroundColor', colorful.fields.RGBColorField(blank=True, default='#FFFFFF', null=True, verbose_name='Background Color')),
                ('textColor', colorful.fields.RGBColorField(blank=True, default='#000000', null=True, verbose_name='Text Color')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('description', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='IvoaEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(1, 'Instrument'), (2, 'Observatory'), (3, 'Mission')], default=1)),
                ('name', models.CharField(max_length=100)),
                ('identifier', models.CharField(blank=True, max_length=200, null=True)),
                ('ivoaEntryId', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('full_text', models.TextField(blank=True, null=True)),
                ('scheme', models.CharField(blank=True, max_length=100, null=True)),
                ('scheme_url', models.URLField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['identifier', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PhenomenaType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('member_image', models.ImageField(blank=True, upload_to=website.models.old.resource_media_directory_path)),
                ('description', models.TextField(max_length=700)),
                ('personal_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=website.models.old.num_team_members, validators=[django.core.validators.MaxValueValidator(website.models.old.num_team_members)])),
                ('previous_order', models.IntegerField(default=-1)),
                ('is_alumnus', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('abbreviation', models.CharField(blank=True, max_length=4)),
                ('theme_color', colorful.fields.RGBColorField(default='#000000')),
                ('text_color', colorful.fields.RGBColorField(default='#ffffff')),
                ('description', models.TextField(blank=True, max_length=700)),
                ('index', models.PositiveIntegerField(blank=True, null=True)),
                ('children', models.ManyToManyField(blank=True, related_name='parents', to='website.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('abbreviation', models.CharField(blank=True, max_length=4)),
                ('theme_color', colorful.fields.RGBColorField(default='#000000')),
                ('text_color', colorful.fields.RGBColorField(default='#ffffff')),
                ('description', models.TextField(blank=True, max_length=700)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('children', models.ManyToManyField(blank=True, related_name='parents', to='website.collection')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Functionality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='functionalities', to='website.functioncategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('published_on', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISH', 'Publish')], default='DRAFT', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_on'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.IntegerField(choices=[(1, 'University'), (2, 'Company'), (3, 'Non-Profit'), (4, 'Government Agency'), (6, 'Other')], default=6)),
                ('website', models.URLField(blank=True, null=True)),
                ('identifier', models.CharField(blank=True, max_length=200, null=True)),
                ('parent_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_organizations', to='website.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FileFormat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extension', models.CharField(max_length=25)),
                ('fullName', models.CharField(blank=True, max_length=100, null=True)),
                ('affiliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_formats', to='website.organization')),
            ],
            options={
                'ordering': ['extension'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('lastName', models.CharField(blank=True, max_length=100, null=True)),
                ('identifier', models.CharField(blank=True, max_length=512, null=True)),
                ('affiliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='website.organization')),
            ],
            options={
                'ordering': ['lastName', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Curator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curators', to='website.person')),
            ],
            options={
                'ordering': ['person'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programming_languages', to='website.organization')),
            ],
            options={
                'ordering': ['name', 'version'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='The name of the resource (limited to 40 characters)', max_length=150, verbose_name='resource name')),
                ('description', models.TextField(blank=True, help_text='A description of the resource <strong>(may contain Markdown; limited to 700 characters)</strong>', max_length=700)),
                ('release_url', models.URLField(blank=True, help_text='<strong> Add one link only - </strong>An (optional) link to the latest release of the resource', verbose_name='Release URL')),
                ('repo_url', models.URLField(blank=True, help_text='<strong> Add one link only - </strong> An (optional) link that points to the github, gitlab, or other public remote repository url for the software. This can also be a link to a binary/other download if source code is not available.', verbose_name='Repository URL')),
                ('docs_url', models.URLField(blank=True, help_text='<strong> Add one link only - </strong>An (optional) link to further information or README about the resource (not the original publication)', verbose_name='Documentation URL')),
                ('website_url', models.URLField(blank=True, help_text='<strong> Add one link only - </strong>An (optional) link to a web-accessible interface for the resource', verbose_name='Website URL')),
                ('author', models.CharField(blank=True, help_text='The developer/researcher credits of the resource (e.g. “Smith, J. et al.” or “The COOL Team”; may contain Markdown)', max_length=256, verbose_name='Author(s)')),
                ('version', models.CharField(blank=True, help_text='The (optional) version number of the resource (name + version must be unique). Updated regularly for github resources with releases.', max_length=20)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last mod date')),
                ('license', models.CharField(blank=True, help_text='The license under which the software is distributed', max_length=256)),
                ('code_language', models.CharField(blank=True, default='', help_text='The primary programming language that the tool is developed in (e.g. Python, R, IDL, etc.)', max_length=256, verbose_name='Code language(s)')),
                ('related_tools', models.CharField(blank=True, default='', help_text='List any tools related to the resource in this submission, i.e. tools that this software has expanded on, tools built off of this software, or tools that work in tandem with this software', max_length=256, verbose_name='Related Tool(s)')),
                ('logo', models.ImageField(blank=True, help_text='Upload an (optional) logo image for the resource (limited to 1MB)', upload_to=website.models.old.resource_media_directory_path)),
                ('logo_url', models.URLField(blank=True, help_text='<strong> Add one link only - </strong>A URL where the logo image can be fetched from (e.g. https://example.com/logo.png)', verbose_name='Logo (URL)')),
                ('search_keywords', models.CharField(blank=True, default='', help_text="Keywords to prioritize in search, seperated by ','", max_length=256, verbose_name='Search Keywords')),
                ('is_published', models.BooleanField(default=False, help_text='Indicates whether this is a published resource')),
                ('status_notes', models.TextField(blank=True)),
                ('spec_community', models.IntegerField(choices=[(3, 'Good'), (2, 'Partially Met'), (1, 'Needs Improvement'), (0, 'Unknown')], default=0, verbose_name='community')),
                ('spec_documentation', models.IntegerField(choices=[(3, 'Good'), (2, 'Partially Met'), (1, 'Needs Improvement'), (0, 'Unknown')], default=0, verbose_name='documentation')),
                ('spec_testing', models.IntegerField(choices=[(3, 'Good'), (2, 'Partially Met'), (1, 'Needs Improvement'), (0, 'Unknown')], default=0, verbose_name='testing')),
                ('spec_maturity', models.IntegerField(choices=[(3, 'Good'), (2, 'Partially Met'), (1, 'Needs Improvement'), (0, 'Unknown')], default=0, verbose_name='maturity')),
                ('categories', models.ManyToManyField(blank=True, help_text='The categories that are applicable to the resource', related_name='+', to='website.category')),
                ('collections', models.ManyToManyField(blank=True, help_text='The collections that are applicable to the resource', related_name='+', to='website.collection')),
                ('related_resources', models.ManyToManyField(blank=True, to='website.resource')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_id_temp', models.CharField(blank=True, max_length=32)),
                ('feedback_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitter_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('provide_demo_video', models.BooleanField(default=False, verbose_name='A demonstration video would be helpful')),
                ('provide_tutorial', models.BooleanField(default=False, verbose_name='A hands-on tutorial would be helpful')),
                ('provide_web_app', models.BooleanField(default=False, verbose_name='A web-accessible application would be helpful')),
                ('relate_a_resource', models.BooleanField(default=False, verbose_name='There is another resource that should be linked as related to this one')),
                ('correction_needed', models.BooleanField(default=False, verbose_name='There is something incorrect in the resource listing')),
                ('comments', models.TextField(blank=True, help_text='Maximum 1500 characters.', max_length=1500, verbose_name='Related comments or additional suggestions:')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='website.resource')),
            ],
            options={
                'verbose_name_plural': 'feedback',
                'ordering': ['-feedback_date'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('name', models.CharField(db_index=True, help_text='The name of the resource (limited to 40 characters)', max_length=150, verbose_name='resource name')),
                ('description', models.TextField(blank=True, help_text='A description of the resource <strong>(may contain Markdown; limited to 700 characters)</strong>', max_length=700)),
                ('release_url', models.URLField(blank=True, help_text='<strong> Add one link only - </strong>An (optional) link to the latest release of the resource', verbose_name='Release URL')),
                ('repo_url', models.URLField(blank=True, help_text='<strong> Add one link only - </strong> An (optional) link that points to the github, gitlab, or other public remote repository url for the software. This can also be a link to a binary/other download if source code is not available.', verbose_name='Repository URL')),
                ('docs_url', models.URLField(blank=True, help_text='<strong> Add one link only - </strong>An (optional) link to further information or README about the resource (not the original publication)', verbose_name='Documentation URL')),
                ('website_url', models.URLField(blank=True, help_text='<strong> Add one link only - </strong>An (optional) link to a web-accessible interface for the resource', verbose_name='Website URL')),
                ('author', models.CharField(blank=True, help_text='The developer/researcher credits of the resource (e.g. “Smith, J. et al.” or “The COOL Team”; may contain Markdown)', max_length=256, verbose_name='Author(s)')),
                ('version', models.CharField(blank=True, help_text='The (optional) version number of the resource (name + version must be unique). Updated regularly for github resources with releases.', max_length=20)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last mod date')),
                ('license', models.CharField(blank=True, help_text='The license under which the software is distributed', max_length=256)),
                ('code_language', models.CharField(blank=True, default='', help_text='The primary programming language that the tool is developed in (e.g. Python, R, IDL, etc.)', max_length=256, verbose_name='Code language(s)')),
                ('related_tools', models.CharField(blank=True, default='', help_text='List any tools related to the resource in this submission, i.e. tools that this software has expanded on, tools built off of this software, or tools that work in tandem with this software', max_length=256, verbose_name='Related Tool(s)')),
                ('logo', models.ImageField(blank=True, help_text='Upload an (optional) logo image for the resource (limited to 1MB)', upload_to=website.models.old.resource_media_directory_path)),
                ('logo_url', models.URLField(blank=True, help_text='<strong> Add one link only - </strong>A URL where the logo image can be fetched from (e.g. https://example.com/logo.png)', verbose_name='Logo (URL)')),
                ('search_keywords', models.CharField(blank=True, default='', help_text="Keywords to prioritize in search, seperated by ','", max_length=256, verbose_name='Search Keywords')),
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('other_category', models.CharField(blank=True, help_text='Suggest a category not listed here', max_length=256)),
                ('submitter_contact', models.CharField(blank=True, help_text='Please provide a way that our team can contact you', max_length=256, verbose_name='contact info')),
                ('submission_notes', models.TextField(blank=True, help_text='Any further information you would like to include with your submission')),
                ('submitter_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Proposed Tool w/ Missing Info'), (1, 'Ready for 1st Contact'), (2, 'Contacted'), (3, 'Tool Development is Paused (Check Submission Notes)'), (4, 'Received'), (5, 'In Review (Our End)'), (6, 'In Review (Their End)'), (7, 'Resource Created'), (8, 'Web Tool Under Development'), (9, 'In Literature Resource Created'), (10, 'Rejected/Abandoned'), (11, 'Spam')], default='Ready for 1st Contact')),
                ('status_notes', models.TextField(blank=True)),
                ('shepherd', models.CharField(blank=True, max_length=40)),
                ('date_contacted', models.DateField(blank=True, null=True)),
                ('has_unsynced_changes', models.BooleanField(default=False, verbose_name='out of sync')),
                ('contact_count', models.IntegerField(default=0, help_text=['Number of times the submitter has been contacted'])),
                ('categories', models.ManyToManyField(blank=True, help_text='The categories that are applicable to the resource', related_name='+', to='website.category')),
                ('collections', models.ManyToManyField(blank=True, help_text='The collections that are applicable to the resource', related_name='+', to='website.collection')),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource', to='website.submission'),
        ),
        migrations.CreateModel(
            name='SubmissionInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateModified', models.DateField(auto_now=True)),
                ('modificationDescription', models.TextField(blank=True, null=True)),
                ('metadataVersionNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('submitterEmail', models.EmailField(max_length=254)),
                ('curatorEmail', models.EmailField(max_length=254)),
                ('submissionDate', models.DateField()),
                ('internalStatusNote', models.TextField(blank=True, null=True)),
                ('lastContactDate', models.DateField(blank=True, null=True)),
                ('contactCount', models.IntegerField(default=0)),
                ('curatorLock', models.BooleanField(default=False)),
                ('outOfSync', models.BooleanField(default=False)),
                ('curator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission_info_owner', to='website.curator')),
                ('leadCurator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission_info_leader', to='website.curator')),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission_info', to='website.person')),
            ],
            options={
                'ordering': ['submissionDate'],
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('publicationDate', models.DateField()),
                ('softwareName', models.CharField(max_length=150)),
                ('versionNumber', models.CharField(blank=True, max_length=25, null=True)),
                ('versionDate', models.DateField(blank=True, null=True)),
                ('versionDescription', models.TextField(blank=True, null=True)),
                ('versionPid', models.CharField(blank=True, max_length=200, null=True)),
                ('persistentIdentifier', models.CharField(blank=True, max_length=200, null=True)),
                ('referencePublication', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('conciseDescription', models.TextField(blank=True, max_length=200, null=True)),
                ('documentation', models.URLField(blank=True, null=True)),
                ('relatedPublications', models.TextField(blank=True, null=True)),
                ('relatedDatasets', models.TextField(blank=True, null=True)),
                ('developmentStatus', models.IntegerField(choices=[(1, 'Concept'), (2, 'WIP'), (3, 'Suspended'), (4, 'Abandoned'), (5, 'Active'), (6, 'Inactive'), (7, 'Unsupported'), (8, 'Moved')], default=2)),
                ('relatedRegion', models.TextField(blank=True, null=True)),
                ('relatedSoftware', models.TextField(blank=True, null=True)),
                ('interopableSoftware', models.TextField(blank=True, null=True)),
                ('codeRepositoryUrl', models.URLField(blank=True, null=True)),
                ('authors', models.ManyToManyField(related_name='softwares', to='website.person')),
                ('award', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='softwares', to='website.award')),
                ('dataInputs', models.ManyToManyField(related_name='softwares_data', to='website.functionality')),
                ('funder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='softwares_funder', to='website.organization')),
                ('keywords', models.ManyToManyField(related_name='softwares', to='website.keyword')),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='softwares_license', to='website.license')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='softwares', to='website.image')),
                ('metadataLicense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='softwares', to='website.license')),
                ('operatingSystem', models.ManyToManyField(related_name='softwares', to='website.operatingsystem')),
                ('programmingLanguage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='softwares', to='website.programminglanguage')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='softwares', to='website.organization')),
                ('relatedInstruments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='softwares', to='website.ivoaentry')),
                ('relatedObservatories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observatories', to='website.ivoaentry')),
                ('relatedPhenomena', models.ManyToManyField(related_name='softwares', to='website.phenomenatype')),
                ('softwareFunctionality', models.ManyToManyField(related_name='softwares', to='website.functionality')),
                ('supportedFileFormats', models.ManyToManyField(related_name='softwares', to='website.fileformat')),
                ('submissionInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='softwares', to='website.submissioninfo')),
            ],
            options={
                'ordering': ['softwareName'],
            },
        ),
        migrations.CreateModel(
            name='ToolType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('abbreviation', models.CharField(blank=True, max_length=4)),
                ('theme_color', colorful.fields.RGBColorField(default='#000000')),
                ('text_color', colorful.fields.RGBColorField(default='#ffffff')),
                ('description', models.TextField(blank=True, max_length=700)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('children', models.ManyToManyField(blank=True, related_name='parents', to='website.tooltype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='tool_types',
            field=models.ManyToManyField(blank=True, help_text='The tool types that are applicable to the resource', related_name='+', to='website.tooltype'),
        ),
        migrations.AddField(
            model_name='resource',
            name='tool_types',
            field=models.ManyToManyField(blank=True, help_text='The tool types that are applicable to the resource', related_name='+', to='website.tooltype'),
        ),
        migrations.CreateModel(
            name='InLitResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='The name of the resource (limited to 40 characters)', max_length=150, verbose_name='resource name')),
                ('description', models.TextField(blank=True, help_text='A description of the resource <strong>(may contain Markdown; limited to 700 characters)</strong>', max_length=700)),
                ('release_url', models.URLField(blank=True, help_text='<strong> Add one link only - </strong>An (optional) link to the latest release of the resource', verbose_name='Release URL')),
                ('repo_url', models.URLField(blank=True, help_text='<strong> Add one link only - </strong> An (optional) link that points to the github, gitlab, or other public remote repository url for the software. This can also be a link to a binary/other download if source code is not available.', verbose_name='Repository URL')),
                ('docs_url', models.URLField(blank=True, help_text='<strong> Add one link only - </strong>An (optional) link to further information or README about the resource (not the original publication)', verbose_name='Documentation URL')),
                ('website_url', models.URLField(blank=True, help_text='<strong> Add one link only - </strong>An (optional) link to a web-accessible interface for the resource', verbose_name='Website URL')),
                ('author', models.CharField(blank=True, help_text='The developer/researcher credits of the resource (e.g. “Smith, J. et al.” or “The COOL Team”; may contain Markdown)', max_length=256, verbose_name='Author(s)')),
                ('version', models.CharField(blank=True, help_text='The (optional) version number of the resource (name + version must be unique). Updated regularly for github resources with releases.', max_length=20)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last mod date')),
                ('license', models.CharField(blank=True, help_text='The license under which the software is distributed', max_length=256)),
                ('code_language', models.CharField(blank=True, default='', help_text='The primary programming language that the tool is developed in (e.g. Python, R, IDL, etc.)', max_length=256, verbose_name='Code language(s)')),
                ('related_tools', models.CharField(blank=True, default='', help_text='List any tools related to the resource in this submission, i.e. tools that this software has expanded on, tools built off of this software, or tools that work in tandem with this software', max_length=256, verbose_name='Related Tool(s)')),
                ('logo', models.ImageField(blank=True, help_text='Upload an (optional) logo image for the resource (limited to 1MB)', upload_to=website.models.old.resource_media_directory_path)),
                ('logo_url', models.URLField(blank=True, help_text='<strong> Add one link only - </strong>A URL where the logo image can be fetched from (e.g. https://example.com/logo.png)', verbose_name='Logo (URL)')),
                ('search_keywords', models.CharField(blank=True, default='', help_text="Keywords to prioritize in search, seperated by ','", max_length=256, verbose_name='Search Keywords')),
                ('is_published', models.BooleanField(default=False, help_text='Indicates whether this is a published resource')),
                ('status_notes', models.TextField(blank=True)),
                ('categories', models.ManyToManyField(blank=True, help_text='The categories that are applicable to the resource', related_name='+', to='website.category')),
                ('collections', models.ManyToManyField(blank=True, help_text='The collections that are applicable to the resource', related_name='+', to='website.collection')),
                ('submission', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='il_resource', to='website.submission')),
                ('tool_types', models.ManyToManyField(blank=True, help_text='The tool types that are applicable to the resource', related_name='+', to='website.tooltype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
