# Generated by Django 5.1.5 on 2025-05-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentobservatory',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='instrumentobservatory',
            name='name',
            field=models.CharField(max_length=512),
        ),
    ]
