# Generated by Django 5.1.5 on 2025-08-08 07:09

import django.db.models.deletion
import website.models.people
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='funder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards', to='website.organization'),
        ),
        migrations.AlterField(
            model_name='curator',
            name='person',
            field=models.OneToOneField(default=website.models.people.Person.get_default_person, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='curator', to='website.person'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='parent_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_organizations', to='website.organization'),
        ),
        migrations.AlterField(
            model_name='relateditem',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatedItems', to='website.license'),
        ),
        migrations.AlterField(
            model_name='software',
            name='developmentStatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='softwares', to='website.repostatus'),
        ),
        migrations.AlterField(
            model_name='software',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='softwares_license', to='website.license'),
        ),
        migrations.AlterField(
            model_name='software',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='softwares', to='website.image'),
        ),
        migrations.AlterField(
            model_name='software',
            name='metadataLicense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='softwares', to='website.license'),
        ),
        migrations.AlterField(
            model_name='software',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='softwares_published', to='website.organization'),
        ),
        migrations.AlterField(
            model_name='software',
            name='referencePublication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='softwares_published', to='website.relateditem'),
        ),
        migrations.AlterField(
            model_name='software',
            name='submissionInfo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software', to='website.submissioninfo'),
        ),
        migrations.AlterField(
            model_name='software',
            name='version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software', to='website.softwareversion'),
        ),
        migrations.AlterField(
            model_name='submissioninfo',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_infos', to='website.curator'),
        ),
        migrations.AlterField(
            model_name='submissioninfo',
            name='leadCurator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_infos_led', to='website.curator'),
        ),
        migrations.AlterField(
            model_name='submissioninfo',
            name='submitter',
            field=models.ForeignKey(blank=True, default=website.models.people.Submitter.get_default_submitter, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='submission_infos', to='website.submitter'),
        ),
        migrations.AlterField(
            model_name='submitter',
            name='person',
            field=models.ForeignKey(default=website.models.people.Person.get_default_person, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='submitter', to='website.person'),
        ),
    ]
