# Generated by Django 5.1.5 on 2025-04-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionality',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='functioncategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
