# Generated by Django 5.1.5 on 2025-02-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='spec_testing',
            field=models.IntegerField(choices=[(3, 'Good'), (2, 'Partially Met'), (1, 'Needs Improvement'), (0, 'Unknown')], default=0, verbose_name='testing'),
        ),
    ]
