# Generated by Django 5.1.4 on 2024-12-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inlitresource',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='The categories that are applicable to the resource', related_name='+', to='website.category'),
        ),
        migrations.AlterField(
            model_name='inlitresource',
            name='collections',
            field=models.ManyToManyField(blank=True, help_text='The collections that are applicable to the resource', related_name='+', to='website.collection'),
        ),
        migrations.AlterField(
            model_name='inlitresource',
            name='tool_types',
            field=models.ManyToManyField(blank=True, help_text='The tool types that are applicable to the resource', related_name='+', to='website.tooltype'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='The categories that are applicable to the resource', related_name='+', to='website.category'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='collections',
            field=models.ManyToManyField(blank=True, help_text='The collections that are applicable to the resource', related_name='+', to='website.collection'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='related_resources',
            field=models.ManyToManyField(blank=True, to='website.resource'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='tool_types',
            field=models.ManyToManyField(blank=True, help_text='The tool types that are applicable to the resource', related_name='+', to='website.tooltype'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='The categories that are applicable to the resource', related_name='+', to='website.category'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='collections',
            field=models.ManyToManyField(blank=True, help_text='The collections that are applicable to the resource', related_name='+', to='website.collection'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='tool_types',
            field=models.ManyToManyField(blank=True, help_text='The tool types that are applicable to the resource', related_name='+', to='website.tooltype'),
        ),
    ]
