# Generated by Django 5.1.5 on 2025-03-21 20:27

import colorful.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_awards_functioncategories_images_ivoaentries_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(blank=True, max_length=5, null=True)),
                ('backgroundColor', colorful.fields.RGBColorField(blank=True, default='#FFFFFF', null=True, verbose_name='Background Color')),
                ('textColor', colorful.fields.RGBColorField(blank=True, default='#000000', null=True, verbose_name='Text Color')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IvoaEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(1, 'Instrument'), (2, 'Observatory'), (3, 'Mission')], default=1)),
                ('name', models.CharField(max_length=100)),
                ('identifier', models.CharField(blank=True, max_length=200, null=True)),
                ('ivoaEntryId', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('full_text', models.TextField(blank=True, null=True)),
                ('scheme', models.CharField(blank=True, max_length=100, null=True)),
                ('scheme_url', models.URLField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['identifier', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='softwares',
            name='supportedFileFormats',
        ),
        migrations.RemoveField(
            model_name='functionalities',
            name='category',
        ),
        migrations.RemoveField(
            model_name='softwares',
            name='dataInputs',
        ),
        migrations.RemoveField(
            model_name='softwares',
            name='softwareFunctionality',
        ),
        migrations.RemoveField(
            model_name='softwares',
            name='relatedObservatories',
        ),
        migrations.RemoveField(
            model_name='softwares',
            name='relatedInstruments',
        ),
        migrations.RemoveField(
            model_name='softwares',
            name='metadataLicense',
        ),
        migrations.RemoveField(
            model_name='softwares',
            name='license',
        ),
        migrations.RemoveField(
            model_name='organizations',
            name='parent_organization',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='affiliation',
        ),
        migrations.RemoveField(
            model_name='programminglanguages',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='softwares',
            name='funder',
        ),
        migrations.RemoveField(
            model_name='softwares',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='softwares',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='softwares',
            name='programmingLanguage',
        ),
        migrations.RemoveField(
            model_name='softwares',
            name='award',
        ),
        migrations.RemoveField(
            model_name='softwares',
            name='developmentStatus',
        ),
        migrations.RemoveField(
            model_name='softwares',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='softwares',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='softwares',
            name='operatingSystem',
        ),
        migrations.RemoveField(
            model_name='softwares',
            name='relatedPhenomena',
        ),
        migrations.CreateModel(
            name='Functionality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='functionalities', to='website.functioncategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.IntegerField(choices=[(1, 'University'), (2, 'Company'), (3, 'Non-Profit'), (4, 'Government Agency'), (6, 'Other')], default=6)),
                ('website', models.URLField(blank=True, null=True)),
                ('identifier', models.CharField(blank=True, max_length=200, null=True)),
                ('parent_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_organizations', to='website.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FileFormat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extension', models.CharField(max_length=25)),
                ('fullName', models.CharField(blank=True, max_length=100, null=True)),
                ('affiliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_formats', to='website.organization')),
            ],
            options={
                'ordering': ['extension'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('lastName', models.CharField(blank=True, max_length=100, null=True)),
                ('identifier', models.CharField(blank=True, max_length=200, null=True)),
                ('affiliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='website.organization')),
            ],
            options={
                'ordering': ['lastName', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programming_languages', to='website.organization')),
            ],
            options={
                'ordering': ['name', 'version'],
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('publicationDate', models.DateField()),
                ('softwareName', models.CharField(max_length=150)),
                ('versionNumber', models.CharField(blank=True, max_length=25, null=True)),
                ('versionDate', models.DateField(blank=True, null=True)),
                ('versionDescription', models.TextField(blank=True, null=True)),
                ('versionPid', models.CharField(blank=True, max_length=200, null=True)),
                ('persistentIdentifier', models.CharField(blank=True, max_length=200, null=True)),
                ('referencePublication', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('conciseDescription', models.TextField(blank=True, max_length=200, null=True)),
                ('documentation', models.URLField(blank=True, null=True)),
                ('relatedPublications', models.TextField(blank=True, null=True)),
                ('relatedDatasets', models.TextField(blank=True, null=True)),
                ('relatedRegion', models.TextField(blank=True, null=True)),
                ('relatedSoftware', models.TextField(blank=True, null=True)),
                ('interopableSoftware', models.TextField(blank=True, null=True)),
                ('codeRepositoryUrl', models.URLField(blank=True, null=True)),
                ('authors', models.ManyToManyField(related_name='softwares', to='website.person')),
                ('award', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='softwares', to='website.awards')),
                ('dataInputs', models.ManyToManyField(related_name='softwares_data', to='website.functionality')),
                ('developmentStatus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='softwares', to='website.repostatuses')),
                ('funder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='softwares_funder', to='website.organization')),
                ('keywords', models.ManyToManyField(related_name='softwares', to='website.keywords')),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='softwares_license', to='website.license')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='softwares', to='website.images')),
                ('metadataLicense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='softwares', to='website.license')),
                ('operatingSystem', models.ManyToManyField(related_name='softwares', to='website.operatingsystems')),
                ('programmingLanguage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='softwares', to='website.programminglanguage')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='softwares', to='website.organization')),
                ('relatedInstruments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='softwares', to='website.ivoaentry')),
                ('relatedObservatories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observatories', to='website.ivoaentry')),
                ('relatedPhenomena', models.ManyToManyField(related_name='softwares', to='website.phenomenatypes')),
                ('softwareFunctionality', models.ManyToManyField(related_name='softwares', to='website.functionality')),
                ('supportedFileFormats', models.ManyToManyField(related_name='softwares', to='website.fileformat')),
            ],
            options={
                'ordering': ['softwareName'],
            },
        ),
        migrations.DeleteModel(
            name='FileFormats',
        ),
        migrations.DeleteModel(
            name='FunctionCategories',
        ),
        migrations.DeleteModel(
            name='Functionalities',
        ),
        migrations.DeleteModel(
            name='IvoaEntries',
        ),
        migrations.DeleteModel(
            name='Licenses',
        ),
        migrations.DeleteModel(
            name='Organizations',
        ),
        migrations.DeleteModel(
            name='Persons',
        ),
        migrations.DeleteModel(
            name='ProgrammingLanguages',
        ),
        migrations.DeleteModel(
            name='Softwares',
        ),
    ]
