# Generated by Django 5.1.5 on 2025-08-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_award_funder_alter_curator_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='publicationDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
