# Generated by Django 5.1.5 on 2025-07-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_software_developmentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='cpuarchitecture',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='datainput',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='fileformat',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='functioncategory',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='instrumentobservatory',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='instrumentobservatory',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='license',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='operatingsystem',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='person',
            name='firstName',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='person',
            name='lastName',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='phenomena',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='version',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='relateditem',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='repostatus',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='software',
            name='softwareName',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='softwareversion',
            name='number',
            field=models.CharField(max_length=256),
        ),
    ]
