# Generated by Django 5.1.5 on 2025-05-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_instrumentobservatory_abbreviation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentobservatory',
            name='definition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instrumentobservatory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
