# Generated by Django 5.1.5 on 2025-08-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_software_publicationdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visiblesoftware',
            options={'verbose_name_plural': 'Visible software'},
        ),
        migrations.AlterField(
            model_name='visiblesoftware',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
