# Generated by Django 5.1.5 on 2025-07-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_award_name_alter_cpuarchitecture_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissioninfo',
            name='submitter',
        ),
        migrations.AddField(
            model_name='submissioninfo',
            name='submitter',
            field=models.ManyToManyField(blank=True, related_name='submission_infos', to='website.submitter'),
        ),
    ]
