# Generated by Django 5.1.5 on 2025-05-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_instrumentobservatory_definition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='identifier',
            field=models.CharField(blank=True, null=True),
        ),
    ]
