# Generated by Django 5.1.5 on 2025-07-22 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_submissioninfo_submitter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softwareversion',
            name='software',
        ),
    ]
