# Generated by Django 5.1.5 on 2025-07-02 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_award_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='supportedFileFormats',
        ),
        migrations.AddField(
            model_name='software',
            name='funder',
            field=models.ManyToManyField(blank=True, related_name='softwares_funded', to='website.organization'),
        ),
        migrations.AddField(
            model_name='software',
            name='outputFormats',
            field=models.ManyToManyField(blank=True, related_name='softwares_from', to='website.fileformat'),
        ),
        migrations.AlterField(
            model_name='software',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='softwares_published', to='website.organization'),
        ),
    ]
