# Generated by Django 5.1.5 on 2025-08-18 02:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_visiblesoftware_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareEditQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
                ('target_software', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission_edit_queue', to='website.software')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
