# Generated by Django 5.1.5 on 2025-08-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_softwareeditqueue'),
    ]

    operations = [
        migrations.CreateModel(
            name='InReviewSoftware',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
