# Generated by Django 5.1.5 on 2025-07-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_software_supportedfileformats_software_funder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='dataInputs',
        ),
        migrations.AddField(
            model_name='software',
            name='dataSources',
            field=models.ManyToManyField(blank=True, related_name='softwares', to='website.datainput'),
        ),
    ]
