# Generated by Django 5.1.5 on 2025-07-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_softwareversion_software'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='programmingLanguage',
        ),
        migrations.AddField(
            model_name='software',
            name='programmingLanguage',
            field=models.ManyToManyField(blank=True, related_name='softwares', to='website.programminglanguage'),
        ),
    ]
