# Generated by Django 5.1.5 on 2025-07-24 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_software_programminglanguage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='cpuArchitecture',
            field=models.ManyToManyField(blank=True, related_name='softwares', to='website.cpuarchitecture'),
        ),
        migrations.AddField(
            model_name='software',
            name='inputFormats',
            field=models.ManyToManyField(blank=True, related_name='softwares_in', to='website.fileformat'),
        ),
        migrations.AlterField(
            model_name='award',
            name='identifier',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.RemoveField(
            model_name='software',
            name='award',
        ),
        migrations.AlterField(
            model_name='software',
            name='interoperableSoftware',
            field=models.ManyToManyField(blank=True, related_name='softwares_interoperable', to='website.relateditem'),
        ),
        migrations.AlterField(
            model_name='software',
            name='outputFormats',
            field=models.ManyToManyField(blank=True, related_name='softwares_out', to='website.fileformat'),
        ),
        migrations.AlterField(
            model_name='software',
            name='referencePublication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='softwares_published', to='website.relateditem'),
        ),
        migrations.AlterField(
            model_name='software',
            name='relatedDatasets',
            field=models.ManyToManyField(blank=True, related_name='softwares_data', to='website.relateditem'),
        ),
        migrations.RemoveField(
            model_name='software',
            name='relatedPublications',
        ),
        migrations.AlterField(
            model_name='software',
            name='relatedSoftware',
            field=models.ManyToManyField(blank=True, related_name='softwares_related', to='website.relateditem'),
        ),
        migrations.AddField(
            model_name='software',
            name='award',
            field=models.ManyToManyField(blank=True, related_name='softwares', to='website.award'),
        ),
        migrations.AddField(
            model_name='software',
            name='relatedPublications',
            field=models.ManyToManyField(blank=True, related_name='softwares_referenced', to='website.relateditem'),
        ),
    ]
