# Generated by Django 5.1.5 on 2025-07-03 22:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_software_datainputs_software_datasources'),
    ]

    operations = [
        migrations.CreateModel(
            name='CpuArchitecture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('identifier', models.URLField(blank=True, null=True)),
                ('definition', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
