# Generated by Django 5.1.5 on 2025-08-21 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_inreviewsoftware'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InReviewSoftware',
        ),
        migrations.AddField(
            model_name='softwareeditqueue',
            name='expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='softwareeditqueue',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
