# Generated by Django 5.1.5 on 2025-07-24 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_software_cpuarchitecture_software_inputformats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='identifier',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='cpuarchitecture',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='datainput',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='fileformat',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='functioncategory',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='instrumentobservatory',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='instrumentobservatory',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='license',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='operatingsystem',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='organization',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='person',
            name='firstName',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='person',
            name='lastName',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='phenomena',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='version',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='relateditem',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='repostatus',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='software',
            name='softwareName',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='software',
            name='version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='software', to='website.softwareversion'),
        ),
        migrations.AlterField(
            model_name='softwareversion',
            name='number',
            field=models.CharField(max_length=128),
        ),
    ]
