# Generated by Django 5.1.5 on 2025-07-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_cpuarchitecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='functioncategory',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parent_categories', to='website.functioncategory'),
        ),
        migrations.AlterField(
            model_name='software',
            name='softwareFunctionality',
            field=models.ManyToManyField(blank=True, related_name='softwares', to='website.functioncategory'),
        ),
        migrations.DeleteModel(
            name='Functionality',
        ),
    ]
