# Generated by Django 5.1.5 on 2025-09-21 04:32

import sortedm2m.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_delete_inreviewsoftware_softwareeditqueue_expiration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='authors',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='softwares', to='website.person'),
        ),
    ]
