# Generated by Django 5.1.5 on 2025-09-21 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_software_authors'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE website_software_authors ADD COLUMN sort_value integer NOT NULL DEFAULT 0;",
            "ALTER TABLE website_software_authors DROP COLUMN sort_value;",
        ),
    ]
