# Generated by Django 5.1.5 on 2025-07-09 21:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_functioncategory_children_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='functioncategory',
            name='children',
        ),
        migrations.CreateModel(
            name='ControlledGraphList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('identifier', models.URLField(blank=True, null=True)),
                ('definition', models.TextField(blank=True, null=True)),
                ('children', models.ManyToManyField(blank=True, related_name='parent_categories', to='website.functioncategory')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
