# Generated by Django 5.1.5 on 2026-01-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_add_sort_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
