# Generated by Django 5.1.5 on 2025-07-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_functioncategory_children_controlledgraphlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='functioncategory',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parent_nodes', to='website.functioncategory'),
        ),
        migrations.DeleteModel(
            name='ControlledGraphList',
        ),
    ]
