# Generated by Django 5.1.5 on 2026-01-16 21:32

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpuarchitecture',
            options={},
        ),
        migrations.AlterModelOptions(
            name='datainput',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fileformat',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keyword',
            options={},
        ),
        migrations.AlterModelOptions(
            name='operatingsystem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='phenomena',
            options={},
        ),
        migrations.AlterModelOptions(
            name='programminglanguage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='relateditem',
            options={},
        ),
        migrations.AddIndex(
            model_name='award',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='award_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='award',
            index=django.contrib.postgres.indexes.GinIndex(fields=['identifier'], name='award_ident_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='cpuarchitecture',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='cpuarch_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='datainput',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='datainput_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='fileformat',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='fileformat_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='fileformat',
            index=django.contrib.postgres.indexes.GinIndex(fields=['extension'], name='fileformat_ext_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='functioncategory',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='functioncat_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='instrumentobservatory',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='instrument_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='instrumentobservatory',
            index=django.contrib.postgres.indexes.GinIndex(fields=['abbreviation'], name='instrument_abbrev_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='keyword_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='license',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='license_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='operatingsystem',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='operatingsystem_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='organization_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=django.contrib.postgres.indexes.GinIndex(fields=['abbreviation'], name='organization_abbrev_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=django.contrib.postgres.indexes.GinIndex(fields=['identifier'], name='organization_ident_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='person',
            index=django.contrib.postgres.indexes.GinIndex(fields=['firstName'], name='person_first_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='person',
            index=django.contrib.postgres.indexes.GinIndex(fields=['lastName'], name='person_last_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='person',
            index=django.contrib.postgres.indexes.GinIndex(fields=['identifier'], name='person_ident_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='phenomena',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='phenomena_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='programminglanguage',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='programminglang_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='region',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='region_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='relateditem',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='relateditem_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='relateditem',
            index=django.contrib.postgres.indexes.GinIndex(fields=['identifier'], name='relateditem_ident_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='repostatus',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='repostatus_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='software',
            index=django.contrib.postgres.indexes.GinIndex(fields=['softwareName'], name='software_softwarename_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='software',
            index=django.contrib.postgres.indexes.GinIndex(fields=['conciseDescription'], name='software_concise_desc_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='software',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description'], name='software_description_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='software',
            index=django.contrib.postgres.indexes.GinIndex(fields=['codeRepositoryUrl'], name='software_repo_url_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='software',
            index=django.contrib.postgres.indexes.GinIndex(fields=['documentation'], name='software_doc_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='software',
            index=django.contrib.postgres.indexes.GinIndex(fields=['licenseFileUrl'], name='software_license_url_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='software',
            index=django.contrib.postgres.indexes.GinIndex(fields=['persistentIdentifier'], name='software_pid_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='softwareversion',
            index=django.contrib.postgres.indexes.GinIndex(fields=['number'], name='softwareversion_number_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
