# Generated by Django 5.1.5 on 2026-02-18 20:02

import sortedm2m.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='softwareFunctionality',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='softwares', to='website.functioncategory'),
        ),
    ]
