# Generated by Django 5.1.5 on 2026-01-14 22:17
# Step 1: Add slug field and populate it (no unique constraint yet)

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """Populate slug field for existing software records."""
    Software = apps.get_model('website', 'Software')
    for software in Software.objects.all():
        base_slug = slugify(software.softwareName)
        if not base_slug:
            base_slug = 'software'
        slug = base_slug
        counter = 1
        while Software.objects.filter(slug=slug).exclude(pk=software.pk).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        software.slug = slug
        software.save()


def reverse_populate_slugs(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_image_url'),
    ]

    operations = [
        # Use CharField first to avoid the _like index issue
        migrations.AddField(
            model_name='software',
            name='slug',
            field=models.CharField(blank=True, max_length=150, default=''),
        ),
        migrations.RunPython(populate_slugs, reverse_populate_slugs),
    ]
