# Generated by Django 5.1.5 on 2026-02-22 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='children',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='inlitresource',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='children',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='collections',
        ),
        migrations.RemoveField(
            model_name='inlitresource',
            name='collections',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='collections',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='inlitresource',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='inlitresource',
            name='tool_types',
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='author',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='related_resources',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='tool_types',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='tool_types',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
        migrations.RemoveField(
            model_name='tooltype',
            name='children',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='InLitResource',
        ),
        migrations.DeleteModel(
            name='NewsItem',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
        migrations.DeleteModel(
            name='ToolType',
        ),
    ]
