# Generated by Django 5.1.5 on 2026-01-14 22:17
# Step 2: Add unique constraint to slug field

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_add_software_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
