# Generated by Django 5.1.5 on 2026-03-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_remove_software_submissioninfo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['family_name', 'given_name'], 'verbose_name_plural': 'People'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='person',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='relateditem',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='relateditem',
            name='creditText',
        ),
        migrations.RemoveField(
            model_name='relateditem',
            name='license',
        ),
        migrations.AddField(
            model_name='person',
            name='family_name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='given_name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
