# Generated by Django 5.1.5 on 2026-03-01 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_person_options_remove_person_firstname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='software',
            options={'ordering': ['software_name'], 'verbose_name_plural': '  Software'},
        ),
        migrations.RenameField(
            model_name='software',
            old_name='programmingLanguage',
            new_name='programming_language',
        ),
        migrations.RenameField(
            model_name='software',
            old_name='publicationDate',
            new_name='publication_date',
        ),
        migrations.RenameField(
            model_name='software',
            old_name='relatedInstruments',
            new_name='related_instruments',
        ),
        migrations.RenameField(
            model_name='software',
            old_name='relatedObservatories',
            new_name='related_observatories',
        ),
        migrations.RenameField(
            model_name='software',
            old_name='conciseDescription',
            new_name='concise_description',
        ),
        migrations.RenameField(
            model_name='software',
            old_name='dataSources',
            new_name='data_sources',
        ),
        migrations.RenameField(
            model_name='software',
            old_name='persistentIdentifier',
            new_name='persistent_identifier',
        ),
        migrations.RenameField(
            model_name='software',
            old_name='referencePublication',
            new_name='reference_publication',
        ),
        migrations.RenameField(
            model_name='software',
            old_name='softwareFunctionality',
            new_name='software_functionality',
        ),
        migrations.RenameField(
            model_name='software',
            old_name='softwareName',
            new_name='software_name',
        ),
        migrations.RenameField(
            model_name='software',
            old_name='cpuArchitecture',
            new_name='cpu_architecture',
        ),
        migrations.RenameField(
            model_name='software',
            old_name='developmentStatus',
            new_name='development_status',
        ),
        migrations.RenameField(
            model_name='software',
            old_name='inputFormats',
            new_name='input_formats',
        ),
        migrations.RenameField(
            model_name='software',
            old_name='operatingSystem',
            new_name='operating_system',
        ),
        migrations.RenameField(
            model_name='software',
            old_name='outputFormats',
            new_name='output_formats',
        ),
        migrations.RenameField(
            model_name='software',
            old_name='relatedDatasets',
            new_name='related_datasets',
        ),
        migrations.RenameField(
            model_name='software',
            old_name='relatedPublications',
            new_name='related_publications',
        ),
    ]
