# Generated by Django 5.1.5 on 2026-03-01 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_rename_programminglanguage_software_programming_language_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissioninfo',
            options={'ordering': ['date_modified'], 'verbose_name_plural': '  Submission Info'},
        ),
        migrations.RenameField(
            model_name='submissioninfo',
            old_name='contactCount',
            new_name='contact_count',
        ),
        migrations.RenameField(
            model_name='submissioninfo',
            old_name='curatorLock',
            new_name='curator_lock',
        ),
        migrations.RenameField(
            model_name='submissioninfo',
            old_name='dateModified',
            new_name='date_modified',
        ),
        migrations.RenameField(
            model_name='submissioninfo',
            old_name='internalStatusCode',
            new_name='internal_status_code',
        ),
        migrations.RenameField(
            model_name='submissioninfo',
            old_name='internalStatusNote',
            new_name='internal_status_note',
        ),
        migrations.RenameField(
            model_name='submissioninfo',
            old_name='lastContactDate',
            new_name='last_contact_date',
        ),
        migrations.RenameField(
            model_name='submissioninfo',
            old_name='leadCurator',
            new_name='lead_curator',
        ),
        migrations.RenameField(
            model_name='submissioninfo',
            old_name='metadataVersionNumber',
            new_name='metadata_version_number',
        ),
        migrations.RenameField(
            model_name='submissioninfo',
            old_name='modificationDescription',
            new_name='modification_description',
        ),
        migrations.RenameField(
            model_name='submissioninfo',
            old_name='outOfSync',
            new_name='out_of_sync',
        ),
        migrations.RenameField(
            model_name='submissioninfo',
            old_name='submissionDate',
            new_name='submission_date',
        ),
    ]
