# Generated by Django 5.1.5 on 2026-03-02 08:00

import uuid, typing
import sortedm2m.fields
import website.models.people
from django.db import migrations, models
from django.apps.registry import Apps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

if typing.TYPE_CHECKING:
    from ..models import SoftwareVersion, Software, SubmissionInfo, Submitter

software_field_map: dict[
    uuid.UUID, 
    tuple[list[uuid.UUID], list[uuid.UUID], list[uuid.UUID], uuid.UUID | None]
] = {}

def create_software_map(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    global software_field_map
    software_field_map = {}
    software_model: type[Software] = apps.get_model("website", "Software")

    for software in software_model.objects.all():
        phenomena = [p.id for p in software.related_phenomena.all()]
        regions = [r.id for r in software.related_region.all()]
        functionality = [f.id for f in software.software_functionality.all()]
        version = software.version.id if software.version else None
        software_field_map[software.id] = (phenomena, regions, functionality, version)

def apply_software_map(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    global software_field_map
    software_model: type[Software] = apps.get_model("website", "Software")
    version_model: type[SoftwareVersion] = apps.get_model("website", "SoftwareVersion")

    through_phenomena: type[models.Model] = (
        software_model._meta.get_field("related_phenomena").remote_field.through
    )
    through_region: type[models.Model] = (
        software_model._meta.get_field("related_region").remote_field.through
    )
    through_functionality: type[models.Model] = (
        software_model._meta.get_field("software_functionality").remote_field.through
    )

    for uid, (phenomena, regions, functionality, version) in software_field_map.items():
        software = software_model.objects.get(id=uid)
        for i, phenom_id in enumerate(phenomena):
            through_phenomena.objects.create(software_id=uid, phenomena_id=phenom_id, sort_value=i)
        for i, region_id in enumerate(regions):
            through_region.objects.create(software_id=uid, region_id=region_id, sort_value=i)
        for i, func_id in enumerate(functionality):
            through_functionality.objects.create(
                software_id=uid, 
                functioncategory_id=func_id, 
                sort_value=i
            )
        if version:
            software.version.add(version_model.objects.get(pk=version))
        software.save()
    del software_field_map

submission_submitter_map: dict[uuid.UUID, uuid.UUID] = {}

def create_submission_submitter_map(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    global submission_submitter_map
    submission_model: type['SubmissionInfo'] = apps.get_model("website", "SubmissionInfo")
    submission_submitter_map = {}
    for sub in submission_model.objects.all():
        submission_submitter_map[sub.pk] = sub.submitter.pk

def apply_submission_submitter_map(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    global submission_submitter_map
    submission_model: type['SubmissionInfo'] = apps.get_model("website", "SubmissionInfo")
    submitter_model: type['Submitter'] = apps.get_model("website", "Submitter")
    for submission_id, submitter_id in submission_submitter_map.items():
        submission = submission_model.objects.get(pk=submission_id)
        submission.submitter.add(submitter_model.objects.get(pk=submitter_id))
        submission.save()
    del submission_submitter_map

class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_rename_programminglanguage_software_programming_language_and_more'),
    ]

    operations = [
        migrations.RunPython(create_software_map),
        migrations.RemoveField(
            model_name='software',
            name='related_phenomena',
        ),
        migrations.AddField(
            model_name='software',
            name='related_phenomena',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='softwares', to='website.phenomena'),
        ),
        migrations.RemoveField(
            model_name='software',
            name='related_region',
        ),
        migrations.AddField(
            model_name='software',
            name='related_region',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='softwares_region', to='website.region'),
        ),
        migrations.RemoveField(
            model_name='software',
            name='software_functionality',
        ),
        migrations.AddField(
            model_name='software',
            name='software_functionality',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='softwares', to='website.functioncategory'),
        ),
        migrations.RemoveField(
            model_name='software',
            name='version',
        ),
        migrations.AddField(
            model_name='software',
            name='version',
            field=models.ManyToManyField(blank=True, null=True, related_name='software', to='website.softwareversion'),
        ),
        migrations.RunPython(apply_software_map),
        migrations.RenameModel(
            old_name='VisibleSoftware',
            new_name='VerifiedSoftware',
        ),
        migrations.AlterField(
            model_name='software',
            name='version',
            field=models.ManyToManyField(blank=True, related_name='software', to='website.softwareversion'),
        ),
        migrations.RunPython(create_submission_submitter_map),
        migrations.RemoveField(
            model_name='organization',
            name='parent_organization',
        ),
        migrations.AlterField(
            model_name='submissioninfo',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='submissioninfo',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='submissioninfo',
            name='submitter',
        ),
        migrations.AddField(
            model_name='submissioninfo',
            name='submitter',
            field=models.ManyToManyField(blank=True, default=website.models.people.Submitter.get_default_submitter, related_name='submission_infos', to='website.submitter'),
        ),
        migrations.RunPython(apply_submission_submitter_map),
        migrations.RemoveField(
            model_name='keyword',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='identifier',
        ),
    ]
