# Generated by Django 5.1.5 on 2026-03-03 06:48
import typing
from django.db import migrations, models
from django.apps.registry import Apps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

from ..models import VerifiedSoftware

if typing.TYPE_CHECKING:
    from ..models import Software

def create_initial_slugs(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    software_model: type[Software] = apps.get_model("website", "Software")
    verified_model: type[VerifiedSoftware] = apps.get_model("website", "VerifiedSoftware")

    for verified in verified_model.objects.all():
        verified.slug = VerifiedSoftware.get_unique_slug(
            software_model.objects.get(pk=verified.pk).software_name
        )
        verified.save()

class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_software_related_phenomena_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verifiedsoftware',
            options={'verbose_name_plural': 'Verified software'},
        ),
        migrations.AddField(
            model_name='verifiedsoftware',
            name='slug',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.RunPython(create_initial_slugs),
    ]
