# Generated by Django 5.1.5 on 2026-03-07 08:16

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_verifiedsoftware_options_verifiedsoftware_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parent_nodes', to='website.region'),
        ),
        migrations.AddField(
            model_name='phenomena',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parent_nodes', to='website.phenomena'),
        ),
    ]
