# Generated by Django 5.1.5 on 2026-06-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_region_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentobservatory',
            name='landing_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
