from enum import Enum

class SaveType(Enum):
    SUBMIT = 0
    EDIT = 1
    NOTIFY = 2
    INITIALINLITCONTACT = 3
    SECONDINLITCONTACT = 4
    FINALINLITCONTACT = 5
    FIRSTCONTACT = 6
    RECONTACT = 7
    FINALCONTACT = 8
    CURATE = 9