from .__old import *
from .software import *
from .submission_info import *
from .organization import *
from .person import *
from .ivoa_entry import *
from .functionality import *
from .basics import *
from .license import *