from django.db import models

from typing import Callable, TYPE_CHECKING
from .software import Software

from ..util import *
from .people import HssiModel, Curator, Submitter

class SubmissionStatusCode(models.IntegerChoices):
	PROPOSED_RESOURCE = 1, "Proposed Resource"
	READY_FOR_CONTACT = 2, "Ready for Contact"
	CONTACTED = 3, "Contacted"
	RESOURCE_DEV_PAUSED = 4, "Resource Dev Paused"
	RECEIVED = 5, "Received"
	IN_REVIEW_INTERNAL = 6, "In Review (Our End)"
	IN_REVIEW_EXTERNAL = 7, "In Review (Their End)"
	RESOURCE_CREATED = 8, "Resource Created (Published)"
	REJECTED = 9, "Rejected/Abandoned"
	SPAM = 10, "Spam"

class SubmissionInfo(HssiModel):
	'''Metadata about the a piece of software submitted to HSSI'''
	access = AccessLevel.CURATOR
	software = models.ForeignKey(
		Software,
		on_delete=models.CASCADE,
		blank=True, null=True,
		related_name='submission_info'
	)
	date_modified = models.DateField(auto_now=True, blank=True, null=True)
	modification_description = models.TextField(blank=True, null=True)
	metadata_version_number = models.CharField(max_length=50, blank=True, null=True)
	submitter = models.ForeignKey(
		Submitter,
		on_delete=models.SET_DEFAULT, 
		default=Submitter.get_default_submitter,
		blank=True,
		related_name='submission_infos'
	)
	curator = models.ForeignKey(
		Curator,
		on_delete=models.SET_NULL, 
		null=True, blank=True, 
		related_name='submission_infos'
	)
	submission_date = models.DateField(blank=True, null=True)
	internal_status_code = models.IntegerField(
		choices=SubmissionStatusCode.choices, 
		default=SubmissionStatusCode.PROPOSED_RESOURCE
	)
	internal_status_note = models.TextField(blank=True, null=True)
	lead_curator = models.ForeignKey(
		Curator,
		on_delete=models.SET_NULL, 
		null=True, blank=True, 
		related_name='submission_infos_led'
	)
	last_contact_date = models.DateField(blank=True, null=True)
	contact_count = models.IntegerField(default=0)
	curator_lock = models.BooleanField(default=False)
	out_of_sync = models.BooleanField(default=False)

	# autogenerated django integer choice string getter
	get_internal_status_code_display: Callable[[], str]

	@classmethod
	def get_top_field(cls) -> models.Field: return cls._meta.get_field("submitter")

	class Meta: 
		ordering = ['date_modified']
		verbose_name_plural = "  Submission Info"
	def __str__(self): 
		text = "Submission"
		if self.submitter: text += f" by {str(self.submitter)}"
		text += f" on {str(self.submission_date)}"
		return text
